# Generated by Django 4.1.5 on 2024-08-25 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menu",
            name="description",
        ),
    ]
