# Generated by Django 4.1.5 on 2023-01-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mydjango", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "poster",
                    models.ImageField(upload_to="movies/", verbose_name="Постер"),
                ),
                ("url", models.SlugField(max_length=130, unique=True)),
                ("draft", models.BooleanField(default=False, verbose_name="Черновик")),
            ],
        ),
        migrations.DeleteModel(
            name="Actor",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Genre",
        ),
        migrations.DeleteModel(
            name="RatingStar",
        ),
    ]
