# Generated by Django 4.1.5 on 2023-01-13 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mydjango", "0002_posting_delete_actor_delete_category_delete_genre_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posting",
            name="poster",
            field=models.ImageField(upload_to="movie/%Y/%m/%d/", verbose_name="Постер"),
        ),
    ]
