# Generated by Django 4.1.5 on 2024-08-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mydjango", "0004_posting_date_posting_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
